//------------------------------------------------------------------------------///------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiculos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class t_ecf_lines_fuel
    {
        public int id { get; set; }
        public Nullable<int> EcfFk { get; set; }
        public Nullable<int> LineNr { get; set; }
        [DisplayName("Matrícula")]
        public string CarRegistration { get; set; }
        [DisplayName("Utilizador")]
        public string User { get; set; }
        [DisplayName("C. Frota")]
        public string FleetCardNo { get; set; }
        [DisplayName("C. Pagamento")]
        public string PaymentCardNo { get; set; }
        [DisplayName("Kms Iniciais")]
        public Nullable<int> KilometersInitial { get; set; }
        [DisplayName("Kms Finais")]
        public Nullable<int> KilometersFinal { get; set; }
        [DisplayName("Litros")]
        public Nullable<double> Liters { get; set; }
        [DisplayName("Valor")]
        public Nullable<double> ExpenseAmount { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Data Abastecimento")]
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        [DisplayName("Obs.")]
        public string Description { get; set; }
        public string VendorNo { get; set; }
        [DisplayName("Fornecedor")]
        public string VendorName { get; set; }
        public string AttachmentPath { get; set; }
        public string Notes { get; set; }
        public string NrEC { get; set; }
        [DisplayName("Litros/100")]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public Nullable<double> Avg { get; set; }
    }

    public partial class t_ecf_lines_fuel
    {
        [NotMapped]
        [DisplayName("Data Pedido")]
        public Nullable<DateTime> TimeStamp { get; set; }
    }
}
