//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiculos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class t_ecf_vehicles
    {
        public int ID { get; set; }
        [DisplayName("Nº")]
        public Nullable<int> No_ { get; set; }
        [DisplayName("Matrícula")]
        [StringLength(50)]
        [Required(ErrorMessage = "Insira a matrícula")]
        public string Matricula { get; set; }
        [StringLength(50)]
        public string Tipo { get; set; }
        [StringLength(50)]
        public string Marca { get; set; }
        [StringLength(50)]
        public string Modelo { get; set; }
        [StringLength(50)]
        public string Categoria { get; set; }
        [DisplayName("Combustível")]
        [StringLength(50)]
        public string Combustivel { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Departamento { get; set; }
        [DisplayName("Responsável")]
        [StringLength(50)]
        public string Responsavel { get; set; }
        [DisplayName("Utilizadores 9-18h")]
        [StringLength(500)]
        public string Utilizadores_9_18 { get; set; }
        [DisplayName("Utilizadores 18-9h")]
        [StringLength(500)]
        public string Utilizadores_18_9 { get; set; }
        [DisplayName("Nº Cartão Pagamento")]
        [StringLength(50)]
        public string NumCartaoPagamento { get; set; }
        [DisplayName("Cartão Pagamento")]
        [StringLength(50)]
        public string RefCartaoPagamento { get; set; }
        [DisplayName("Nº Cartão Frota")]
        [StringLength(50)]
        public string NumCartaoFrota { get; set; }
        [DisplayName("Cartão Frota")]
        [StringLength(50)]
        public string RefCartaoFrota { get; set; }
        [DisplayName("Kms")]
        public Nullable<int> Kilometros { get; set; }
        [DisplayName("Plafond Mensal")]
        public Nullable<double> PlafondMensal { get; set; }
        [DisplayName("Obs.")]
        [StringLength(500)]
        public string Observacoes { get; set; }
        [StringLength(100)]
        public string Car { get; set; }
        public bool Activo { get; set; }

        public virtual t__companies t__companies { get; set; }
        public virtual t__departments t__departments { get; set; }

        public string SubstrObservacoes
        {
            get
            {
                if (String.IsNullOrEmpty(this.Observacoes)) return "";
                return this.Observacoes.Substring(0, this.Observacoes.Length > 22 ? 19 : this.Observacoes.Length) + (this.Observacoes.Length > 19 ? "..." : "");
            }
        }

        public string SubstrUtil9_18
        {
            get
            {
                if (String.IsNullOrEmpty(this.Utilizadores_9_18)) return "";
                return this.Utilizadores_9_18.Substring(0, this.Utilizadores_9_18.Length > 25 ? 22 : this.Utilizadores_9_18.Length) + (this.Utilizadores_9_18.Length > 25 ? "..." : "");
            }
        }

        public string SubstrUtil18_9
        {
            get
            {
                if (String.IsNullOrEmpty(this.Utilizadores_18_9)) return "";
                return this.Utilizadores_18_9.Substring(0, this.Utilizadores_18_9.Length > 25 ? 22 : this.Utilizadores_18_9.Length) + (this.Utilizadores_18_9.Length > 25 ? "..." : "");
            }
        }

        public string SubstrEmpresa
        {
            get
            {
                if (String.IsNullOrEmpty(this.t__companies.CompDescription)) return "";
                return this.t__companies.CompDescription.Substring(0, this.t__companies.CompDescription.Length > 23 ? 20 : this.t__companies.CompDescription.Length) + (this.t__companies.CompDescription.Length > 23 ? "..." : "");
            }
        }

        public string SubstrDepartamento
        {
            get
            {
                if (String.IsNullOrEmpty(this.t__departments.department_pt)) return "";
                return this.t__departments.department_pt.Substring(0, this.t__departments.department_pt.Length > 20 ? 17 : this.t__departments.department_pt.Length) + (this.t__departments.department_pt.Length > 20 ? "..." : "");
            }
        }

        public static t_ecf_vehicles FindVehicle(int? id)
        {
            vdlwebcontrolEntities db = new vdlwebcontrolEntities();
            return db.t_ecf_vehicles.Find(id);
        }
    }
}
