//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ecf_header
    {
        public int id { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> UserIdExpenses { get; set; }
        public Nullable<int> VDLCompany { get; set; }
        public string Comments { get; set; }
        public string NrECEmployee { get; set; }
        public string Type { get; set; }
    }
}
