//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiculos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vdlwebcontrolEntities : DbContext
    {
        public vdlwebcontrolEntities()
            : base("name=vdlwebcontrolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t__companies> t__companies { get; set; }
        public virtual DbSet<t__departments> t__departments { get; set; }
        public virtual DbSet<t_ecf_vehicles> t_ecf_vehicles { get; set; }
        public virtual DbSet<t_ecf_vehicle_types> t_ecf_vehicle_types { get; set; }
        public virtual DbSet<t_ecf_lines_fuel> t_ecf_lines_fuel { get; set; }
        public virtual DbSet<t_ecf_header> t_ecf_header { get; set; }
    }
}
